export default {
    'Signed Language': [
        'British Sign Language (BSL)',
        'Irish Sign Language (ISL)',
        'American Sign Language (ASL)',
        'Other Sign Language',
    ],
    'Spoken Language': [
        'English',
        'Arabic',
        'Bengali',
        'Bulgarian',
        'Cantonese',
        'French',
        'German',
        'Greek',
        'Gujarati',
        'Hindi',
        'Italian',
        'Kurdish',
        'Mandarin',
        'Nepali',
        'Persian (Farsi)',
        'Polish',
        'Portuguese',
        'Punjabi',
        'Romanian',
        'Russian',
        'Somali',
        'Spanish',
        'Tamil',
        'Telugu',
        'Turkish',
        'Ukrainian',
        'Urdu',
        'Vietnamese',
        'Welsh',
        'Yoruba',
        'Other Spoken Language',
    ],
};
