export default {
    Cardiovascular: [
        'Coronary heart disease',
        'Heart failure',
        'Atrial fibrillation',
        'Hypertension (high blood pressure)',
        'High cholesterol',
        'Peripheral arterial disease',
        'Stroke / TIA (transient ischaemic attack)',
        'Deep vein thrombosis (DVT)',
        'Pulmonary embolism',
    ],
    Respiratory: [
        'Asthma',
        'Chronic obstructive pulmonary disease (COPD)',
        'Bronchiectasis',
        'Pulmonary fibrosis',
        'Pulmonary hypertension',
        'Obstructive sleep apnoea',
        'Cystic fibrosis',
    ],
    'Metabolic & Endocrine': [
        'Type 1 diabetes',
        'Type 2 diabetes',
        'Gestational diabetes',
        'Hypothyroidism (underactive thyroid)',
        'Hyperthyroidism (overactive thyroid)',
        "Addison's disease",
        "Cushing's syndrome",
        'Polycystic ovary syndrome (PCOS)',
    ],
    Neurological: [
        'Epilepsy',
        'Multiple sclerosis (MS)',
        "Parkinson's disease",
        'Motor neurone disease (MND)',
        'Migraine',
        'Neuropathy',
        'Narcolepsy',
        'Cerebral palsy',
        "Huntington's disease",
        'Myasthenia gravis',
    ],
    'Mental Health': [
        'Depression',
        'Anxiety disorder',
        'Bipolar disorder',
        'Schizophrenia',
        'Post-traumatic stress disorder (PTSD)',
        'Obsessive-compulsive disorder (OCD)',
        'Borderline personality disorder (BPD)',
        'Eating disorder',
        'Attention deficit hyperactivity disorder (ADHD)',
        'Autism spectrum disorder (ASD)',
    ],
    Musculoskeletal: [
        'Rheumatoid arthritis',
        'Osteoarthritis',
        'Osteoporosis',
        'Ankylosing spondylitis',
        'Psoriatic arthritis',
        'Gout',
        'Fibromyalgia',
        'Lupus (systemic lupus erythematosus)',
        'Scoliosis',
    ],
    Gastrointestinal: [
        "Crohn's disease",
        'Ulcerative colitis',
        'Irritable bowel syndrome (IBS)',
        'Coeliac disease',
        'Gastro-oesophageal reflux disease (GORD)',
        'Peptic ulcer disease',
        'Diverticular disease',
        'Non-alcoholic fatty liver disease (NAFLD)',
        'Cirrhosis of the liver',
        'Hepatitis B',
        'Hepatitis C',
    ],
    'Renal & Urological': [
        'Chronic kidney disease (CKD)',
        'Kidney stones',
        'Polycystic kidney disease',
        'Urinary incontinence',
        'Interstitial cystitis',
        'Benign prostatic hyperplasia (BPH)',
    ],
    Dermatological: [
        'Psoriasis',
        'Eczema (atopic dermatitis)',
        'Rosacea',
        'Vitiligo',
        'Hidradenitis suppurativa',
        'Acne (severe/chronic)',
    ],
    Haematological: [
        'Anaemia',
        'Sickle cell disease',
        'Thalassaemia',
        'Haemophilia',
        'von Willebrand disease',
        'Polycythaemia vera',
    ],
    'Immunological & Autoimmune': [
        'HIV/AIDS',
        'Common variable immunodeficiency (CVID)',
        'Antiphospholipid syndrome',
        "Sjögren's syndrome",
        'Vasculitis',
        'Sarcoidosis',
    ],
    Cancer: [
        'Breast cancer',
        'Prostate cancer',
        'Lung cancer',
        'Bowel (colorectal) cancer',
        'Skin cancer (melanoma)',
        'Leukaemia',
        'Lymphoma',
        'Other cancer',
    ],
    Sensory: ['Glaucoma', 'Macular degeneration', 'Cataracts', 'Hearing loss'],
    Other: [
        'Chronic fatigue syndrome (ME/CFS)',
        "Dementia / Alzheimer's disease",
        'Long COVID',
        'Chronic pain condition',
        'Substance use disorder',
        'Other',
    ],
};
